import raw from "./eps-carparks.json";
import aliasJson from "./eps-aliases.json";
import manualAliasJson from "./eps-aliases-manual.json";
import suppressedJson from "./eps-suppressed.json";
import type { LatLng } from "../geo";

/**
 * LTA EPS car park inventory — the full national list of car parks in the EPS
 * (Electronic Parking System) programme, scraped once from
 * https://eps.lta.gov.sg/EPS_ESERVICES/CarPark (the OutSystems SPA's
 * DataActionGetDetails response).
 *
 * This is an INVENTORY, not rates: it gives name, address, postal code and
 * coordinates so these car parks can be found near a destination, but carries
 * no pricing. A rate can be filled in later per car park via the in-app web
 * lookup or a manual entry. Refresh by re-scraping and regenerating
 * eps-carparks.json.
 */
export interface EpsCarpark {
  id: string;
  name: string;
  address: string;
  postal: string | null;
  location: LatLng;
  /** Public (short-term) parking capacity; null when the feed reports -1/NA. */
  publicLots: number | null;
}

interface RawEps {
  id: string;
  name: string;
  address: string;
  postal: string | null;
  lat: number;
  lng: number;
  publicLots: number | null;
}

/**
 * A handful of CapitaLand-managed sites are listed with a trailing " - C"
 * (the car-park tier, vs the motorcycle/lorry tiers on the operator's own
 * site). There's no matching " - M"/" - L" in this feed, so it's just noise on
 * the display name — drop it.
 */
function cleanName(name: string): string {
  return name.replace(/\s*-\s*C$/i, "").trim();
}

/**
 * Nine URA short-term car parks are listed under URA's internal code —
 * "URA_P0075" — which reaches a card as "Ura_p0075" and tells a driver
 * nothing. The address carries the real identity ("51, LAVENDER STREET,
 * P0075"), so use that, dropping the trailing repeat of the code and joining a
 * bare house number onto its street.
 */
/**
 * Is this a filing code rather than a place? "URA_P0075", "CP13_CP14_CP15",
 * "HDH203", "TP57_TP59" — operators file car parks under internal references
 * and EPS passes them through, so they reach a card as "Ura_p0075" and tell a
 * driver nothing.
 *
 * Chasing them one prefix at a time didn't work: a sweep of the inventory found
 * thirteen across eight different prefixes beyond the two already handled. So
 * the test is structural — every part is a short reference and at least one
 * carries a digit. Requiring the digit is what keeps real names out: "AMOY ST"
 * and "112 KATONG" both survive it.
 */
function isCodeName(name: string): boolean {
  const tokens = name.toUpperCase().trim().split(/[_\s-]+/).filter(Boolean);
  if (!tokens.length) return false;
  const isRef = (t: string) =>
    /^[A-Z]{1,4}\d{1,5}$/.test(t) || /^\d{1,5}[A-Z]?$/.test(t) || /^(HDB|URA|CP|MSCP|BLK)$/.test(t);
  return tokens.every(isRef) && tokens.some((t) => /\d/.test(t));
}

/**
 * EPS uses "_" as filing punctuation inside real names too: "28_30 BIDEFORD
 * ROAD" is two house numbers, "ARAB_ QUEEN STREET" two roads, "47 JALAN
 * PEMIMPIN_ 39A JALAN PEMIMPIN" two addresses sharing one car park. Rewrite in
 * the convention the HDB dataset already uses on cards ("Blk 175/183 To 185"):
 * a slash between numbers, a spaced slash between words.
 */
function tidySeparators(s: string): string {
  if (!s.includes("_")) return s;
  return s
    .replace(/(\d[A-Z]?)\s*_\s*(?=\d)/gi, "$1/")
    .replace(/\s*_\s*/g, " / ")
    .replace(/\s{2,}/g, " ")
    .trim();
}

export function displayName(name: string, address: string): string {
  const clean = cleanName(name);
  // HDB codes are left exactly as they are: publicEpsCarparks filters on this
  // name, so renaming them would defeat isHdbCode and let 1,298 duplicates of
  // the HDB dataset back into search.
  if (/^HDB[_ ]/i.test(clean)) return clean;
  if (!isCodeName(clean)) return tidySeparators(clean);
  // Every part of the code, so the address doesn't just repeat it back.
  const codes = new Set(clean.toUpperCase().split(/[_\s-]+/).filter(Boolean));
  const parts = address
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean)
    .filter((s) => !codes.has(s.toUpperCase()) && !/^singapore\b/i.test(s));
  // "0, TIONG BAHRU ROAD" — a placeholder house number, not an address.
  if (parts[0] === "0") parts.shift();
  if (!parts.length) return clean;
  if (parts.length > 1 && /^\d+[A-Z]?$/i.test(parts[0]!)) {
    return [`${parts[0]} ${parts[1]}`, ...parts.slice(2)].join(", ");
  }
  return parts.join(", ");
}

/**
 * Names resolved from the car park's own postal code, generated by
 * `scripts/epsNameFix.ts` and committed so a human reads the diff.
 *
 * `isCodeName` only rewrites references that carry a digit — the digit is what
 * keeps "AMOY ST" from being mangled — so a purely alphabetic code slips
 * through and reaches a card as written: "TLF", "KBIB", "LSBC". The address
 * cannot fix those because it repeats the code back ("1, CLUNY ROAD, TLF,
 * Singapore 259569"); the POSTAL can, and 259569 is Singapore Botanic Gardens.
 *
 * A shape-based rule would have been wrong here. Most of these acronyms are
 * real names — NEX, JEM, AMK HUB, CITY GATE — and the generator confirms that
 * by finding the postal agrees with the existing name, rather than by me
 * deciding which ones look fake.
 */
/**
 * Hand-written names for the few the postal cannot reach, kept in a separate
 * file so regenerating the derived ones never silently drops them.
 *
 * These are JUDGEMENT, not evidence, and the bar is correspondingly high: the
 * abbreviation must be unambiguous and the location must corroborate it.
 *
 * - 2 "HSO CAR PARK" at 1 Hampshire Road. Its coordinates are right — 5 m from
 *   OneMap's Blk 1, and the postal 219428 matches — so only the name is
 *   opaque. `epsNameFix` correctly refuses OneMap's own answer here, "BLK 1
 *   (LAND TRANSPORT AUTHORITY) (LTA)": a block reference is not a better name
 *   and the doubled parenthetical reads as broken. This keeps that answer's
 *   CONTENT and drops its filing, which is a tidy of the evidence rather than
 *   a guess about what HSO stands for — nothing in the data says.
 *
 * - 1245 "URA_B0096" reaches a card as "114 UPPER BUKIT TIMAH ROAD", which is
 *   not where it is and not a place that exists — OneMap returns nothing for
 *   that address. Its EPS address is simply junk, and `displayName` substitutes
 *   the address whenever the name is a code, so the junk propagated. The
 *   COORDINATES are right: they sit on The URA Centre at 45 Maxwell Road, 101 m
 *   from MND Complex, which is why it surfaces on an MND search. The owner
 *   confirms URA and MND share the one car park, so it is named for both.
 *
 * - 4383 "BTC_NUS" at 1 Cluny Road. Its postal (259659) answers with
 *   "19 CLUNY HILL" and no building name, and OneMap has no entry for NUS's
 *   Bukit Timah Campus at all, so the generator correctly refuses it — an
 *   address is not a better name. BTC is the university's own long-standing
 *   abbreviation for that campus, the row literally reads "BTC_NUS", and it
 *   sits beside the campus. Left as filed it reaches a card as "Btc / Nus",
 *   which also makes it unsearchable when looking up its rate.
 */
const aliases: Record<string, string> = {
  ...(aliasJson as Record<string, string>),
  ...(manualAliasJson as Record<string, string>),
};

const all: EpsCarpark[] = (raw as RawEps[]).map((c) => ({
  id: c.id,
  name: aliases[String(c.id)] ?? displayName(c.name, c.address),
  address: c.address,
  postal: c.postal,
  location: { lat: c.lat, lng: c.lng },
  publicLots: c.publicLots,
}));

/** The complete inventory (all ~3,167 car parks, including season-only ones). */
export const allEpsCarparks: EpsCarpark[] = all;

/**
 * EPS lists HDB car parks under their internal code instead of a name, e.g.
 * "HDB_J4_J5" (which is really Blk 201 Jurong East Street 21). Half this feed
 * is such entries, and ~88% of them sit within 100 m of a car park the HDB
 * dataset already covers properly — with a readable name, live lot counts and
 * a computed rate. Surfacing them again would show an unreadable code with no
 * rate, so they're excluded from search; the HDB source owns those car parks.
 */
function isHdbCode(name: string): boolean {
  return /^HDB[_ ]/i.test(name);
}

/** "…HEAVY VEHICLE" / "LORRY PARK" — a car can't park there. */
function isHeavyVehicleOnly(name: string): boolean {
  return /\b(heavy vehicle|lorry|container)\b/i.test(name);
}

/**
 * Car parks worth surfacing as parking options.
 *
 * `publicLots` used to gate this, on the reading that 0 meant season-only. It
 * doesn't: CT Hub 2 is listed with 0 and takes hourly public parking, and so is
 * "100 Pasir Panjang", for which we already hold a rate. The flag was hiding
 * 1,241 non-HDB car parks, 712 of them nowhere near anything we can price — so
 * it was removing them from the map as well as from the price list.
 *
 * They carry no rate, so they arrive as "location only" cards. Two things stop
 * that swamping a search: the result list sorts priced cards above unpriced
 * ones, and search fills its slots with car parks it can price before it falls
 * back to this inventory.
 *
 * Still excluded: the HDB-coded duplicates above, and heavy-vehicle parks.
 */
/**
 * EPS entries confirmed NOT to be public car parks, with the reason in the file
 * beside each id.
 *
 * A judgement, like the manual aliases, and held to the same bar: the entry has
 * to be wrong in a way the data itself cannot settle. URA_P0013 is filed at
 * "31, SHENTON WAY", which is the Shenton Way Bus Terminal — its coordinates
 * land exactly on the terminal, it carries no rate and no lot count, and the
 * real URA off-street car park sits 98 m away, already listed under its own
 * name.
 *
 * Suppressing rather than renaming, because a better name would still put a
 * card on a bus terminal. Reversible, and the reason is recorded so the next
 * reader can disagree with it.
 *
 * NOT a lever for tidying: 0 public lots means "not stated" in this feed for
 * 1,205 of 1,587 surfaced rows, so it is evidence of nothing on its own.
 */
const suppressed = new Set(Object.keys(suppressedJson as Record<string, string>));

export const publicEpsCarparks: EpsCarpark[] = all.filter(
  (c) => !isHdbCode(c.name) && !isHeavyVehicleOnly(c.name) && !suppressed.has(String(c.id)),
);
